############################################################################
#              AntiCombatUpdate - For angry players with 1.9               #
#                 Values of configuration for plugins                      #
#                Language is supported in this plugin                      #
############################################################################

